name: kubespray offline release

on:
  release:
    # published: A release, pre-release, or draft of a release was published.
    types: [published]

jobs:
  release:
    strategy:
      matrix:
        # Include amd64 and arm64 on linux platform.
        arch: [amd64, arm64]
      fail-fast: false

    runs-on: ubuntu-22.04
    env:
      ARCH: ${{ matrix.arch }}
      REGISTRY_NAME: registry
      REGISTRY_ADDR: 127.0.0.1:5000
      KUBESPRAY_OFFLINE_ARCHIVE: kubespray-offline-${{ github.ref_name }}-${{ matrix.arch }}.tar.gz

    services:
      registry:
        image: "registry:2"
        ports:
          - "127.0.0.1:5000:5000"
        options: --name registry

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate files.list and images.list
        shell: bash
        run: |
          cd contrib/offline && ./generate_list.sh -e host_architecture=${ARCH} && cd ../../

      - name: Download offline files and images
        shell: bash
        run: |
          cd contrib/offline && ./download-offline-files.sh && cd ../../

      - name: Make archive for downloaded resources
        shell: bash
        run: |
          cd contrib/offline
          tar -czf "../../${KUBESPRAY_OFFLINE_ARCHIVE}" kubespray-offline/
          cd ../../

          sha256sum "${KUBESPRAY_OFFLINE_ARCHIVE}" | tee "${KUBESPRAY_OFFLINE_ARCHIVE}.sha256"

          # Each file included in a release must be under 2 GB.
          # There is no limit on the total size of a release, nor bandwidth usage.
          if [ "$(stat --format=%s ${KUBESPRAY_OFFLINE_ARCHIVE})" -ge 2000000000 ]; then
            split --numeric-suffixes=1 --bytes=1G "${KUBESPRAY_OFFLINE_ARCHIVE}" "${KUBESPRAY_OFFLINE_ARCHIVE}."
            rm -f "${OFFLINE_FILES_ARCHIVE}"
          fi

      - name: Upload files to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ${{ env.KUBESPRAY_OFFLINE_ARCHIVE }}.*
